config/routes.rb
Rails.application.routes.draw do
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

  get "/chats/:chat_id/messages" => "messages#index"
  post "/chats/:chat_id/messages" => "messages#create"

  resources :users, only: [:update, :destroy, :show]
  resources :matches, only: [:index, :create, :update, :destroy]
  root to: "static#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SongBirdz</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', "https://fonts.googleapis.com/icon?family=Material+Icons" %>
    <%= stylesheet_link_tag  'application', "https://fonts.googleapis.com/css?family=Roboto:300,400" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <body>
    <nav class="nav-bar">
      <div id="menu" class="menu">
        <a class="sitename" href=""><span class="header">SongBirdz </span><br/><span class="subheader">for love and music</span></a>
        <a class="show" href="#menu"><i class="material-icons md-light">face</i></a><a class="hide" href="#hidemenu"><i class="material-icons">menu</i></a>
        <ul class="menu-items">
          <% if current_user %>
            <li><%= link_to " #{current_user.name}", current_user %></li>
            <li><%= link_to "Matches", matches_path %></li>
            <li><%= link_to "Sign Out", signout_path %></li>
          <% else %>
            <li><%= link_to "Sign in with Spotify", "/auth/spotify" %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <section class="content">
      </div>
      <div id="yield">
        <%= yield %>
      </div>
    </section>
    <div class="color-key">
        <span>Match Affinity</span>
        <ul>
          <li class="purple">Purple: Your song matches their top song </li>
          <li class="blue">Blue: One of your songs matches a song on their Birdlist </li>
          <li class="green">Green: You are matched with this pair  </li>
        </ul>
      </div>
  </body>
</html>